excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://BioSocialChange.github.io
title: BioSocialChange
tagline: A log of everyday life
description: My awesome new site
paginate: 5